### ISSUE TITLE
Memory leak in fbw_cuda

### ISSUE THREAD

**Issue by BenediktConze** [rwth-i6/i6_native_ops#7]
`d_state_buffer_prev` and `d_state_buffer_next` are allocated at https://github.com/rwth-i6/i6_native_ops/blob/200c6bbb91631661a7ee724fb3667ae7770d7b8f/i6_native_ops/fbw/fbw_op.cu#L283-L284, but never freed.

**Comment by DanEnergetics** [comment]
Good catch!
In the TF Version for RETURNN there was a state buffer initialized outside of the CUDA Op that was otherwise not needed I think. @curufinwe, do you know why it was implemented like that back then? I'm wondering if there's something to improve additionally to fixing the memory leak
